base_dir: "/mnt/public/hxy/diff_data/quantile_uniform/" # path to preprocessed data
experiment_name: "quantile_uniform"
seed: 0

model_type: "mlp"

model_params:
  d_y: 3
  is_y_cond: true
  d_embedding: 192
  is_embedding_cond: true
  rtdl_params:
    d_layers: [1024, 1024, 1024, 512]
    dropout: 0.0
  dim_t: 128
  padding_to: 1024
  padding_value: 0.0

steps : 5000
lr: 1e-4
batch_size_per_gpu: 2048
gradient_accumulate_every: 2
ema_update_every: 10
ema_decay: 0.995
adam_betas: [0.9, 0.99]
weight_decay: 1e-4
amp: True
mixed_precision_type: "fp16"
split_batches: true
max_grad_norm: 1.0
save_and_sample_every: 1000
num_samples: 9
results_base_dir: "./results" # results will be saved in results_base_dir/experiment_name
num_timesteps: 1000
gaussian_loss_type: "mse"
scheduler: "cosine"